"use client";

/**
 * Table export helpers — CSV is generated by hand (UTF-8 BOM so Excel opens
 * it cleanly); .xlsx goes through SheetJS, imported on demand so the library
 * never lands in the page bundle unless someone actually exports.
 */

export type ExportRow = Record<string, string | number | boolean | null | undefined>;

function download(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/** Filename-safe slug with today's date, e.g. "name-search-2026-07-13". */
export function exportFilename(base: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const slug = base.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `sprintcheck-${slug}-${date}`;
}

function csvCell(value: ExportRow[string]): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Union of keys across all rows, in first-seen order. */
function collectHeaders(rows: ExportRow[]): string[] {
  const headers: string[] = [];
  const seen = new Set<string>();
  for (const row of rows) {
    for (const key of Object.keys(row)) {
      if (!seen.has(key)) {
        seen.add(key);
        headers.push(key);
      }
    }
  }
  return headers;
}

export function exportCsv(rows: ExportRow[], baseName: string): void {
  const headers = collectHeaders(rows);
  const lines = [
    headers.map(csvCell).join(","),
    ...rows.map((row) => headers.map((h) => csvCell(row[h])).join(",")),
  ];
  // ﻿ BOM makes Excel detect UTF-8 instead of mangling accented text.
  const blob = new Blob(["﻿" + lines.join("\r\n")], {
    type: "text/csv;charset=utf-8",
  });
  download(blob, `${exportFilename(baseName)}.csv`);
}

export async function exportExcel(
  rows: ExportRow[],
  baseName: string,
  sheetName = "Results",
): Promise<void> {
  const XLSX = await import("xlsx");
  const headers = collectHeaders(rows);
  const sheet = XLSX.utils.json_to_sheet(rows, { header: headers });
  const book = XLSX.utils.book_new();
  // Sheet names are capped at 31 chars by the xlsx format.
  XLSX.utils.book_append_sheet(book, sheet, sheetName.slice(0, 31));
  XLSX.writeFile(book, `${exportFilename(baseName)}.xlsx`);
}
